import { Dish, Review, GalleryItem } from './types';

export const DISHES: Dish[] = [
  {
    id: 'd1',
    name: 'Truffle Garlic Bread',
    description: 'Warm toasted rustic sourdough baguette with black truffle butter, roasted farm garlic, and melted buffalo mozzarella.',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?auto=format&fit=crop&q=80&w=600',
    category: 'starters',
    isPopular: false,
    preparationTime: '10 mins',
    rating: 4.7,
  },
  {
    id: 'd2',
    name: 'Tuscan Bruschetta',
    description: 'Crisp rustic bread rubbed with garlic, loaded with marinated heirloom cherry tomatoes, basil pesto, and aged balsamic reduction.',
    price: 10.49,
    image: 'https://images.unsplash.com/photo-1572448862527-d3c904757de6?auto=format&fit=crop&q=80&w=600',
    category: 'starters',
    isPopular: false,
    preparationTime: '8 mins',
    rating: 4.6,
  },
  {
    id: 'd3',
    name: 'Creamy Alfredo Pasta',
    description: 'Rich fettuccine tossed in dynamic double cream, aged parmesan cheese sauce, loaded with fresh minced garlic and flat-leaf parsley.',
    price: 12.99,
    image: '/src/assets/images/creamy_alfredo_1781958600642.jpg',
    category: 'mains',
    isPopular: true,
    preparationTime: '15 mins',
    rating: 4.9,
  },
  {
    id: 'd4',
    name: 'Classic Beef Burger',
    description: 'Succulent double smash beef patties, melted sharp cheddar, vine-ripened tomatoes, crisp romaine, and caramelized onions on toasted brioche.',
    price: 11.99,
    image: '/src/assets/images/beef_burger_1781958615596.jpg',
    category: 'mains',
    isPopular: true,
    preparationTime: '12 mins',
    rating: 4.8,
  },
  {
    id: 'd5',
    name: 'Grilled Salmon Fillet',
    description: 'Perfectly pan-seared King salmon, crispy skin, served with roasted green asparagus spears, fresh lemon segment, and dill butter sauce.',
    price: 15.99,
    image: '/src/assets/images/grilled_salmon_1781958630357.jpg',
    category: 'mains',
    isPopular: true,
    preparationTime: '18 mins',
    rating: 4.9,
  },
  {
    id: 'd6',
    name: 'Molten Chocolate Lava Cake',
    description: 'Decadent dark chocolate sponge cake with liquid fudge center, served warm with vanilla bean gelato and a fresh organic strawberry.',
    price: 6.99,
    image: '/src/assets/images/chocolate_lava_cake_1781958645636.jpg',
    category: 'desserts',
    isPopular: true,
    preparationTime: '14 mins',
    rating: 4.9,
  },
  {
    id: 'd7',
    name: 'Vanilla Bean Panna Cotta',
    description: 'Silky smooth classic cooked Italian cream, infused with authentic Madagascar vanilla, accompanied by organic wild berry soup.',
    price: 7.49,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=600',
    category: 'desserts',
    isPopular: false,
    preparationTime: '8 mins',
    rating: 4.7,
  },
  {
    id: 'd8',
    name: 'Golden Ginger Mimosa',
    description: 'Sparkling refreshing cocktail with premium prosecco, organic citrus orange juice, and a zest of raw hand-pressed ginger roots.',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&q=80&w=600',
    category: 'drinks',
    isPopular: false,
    preparationTime: '5 mins',
    rating: 4.5,
  },
];

export const GALLERY: GalleryItem[] = [
  {
    id: 'g1',
    image: '/src/assets/images/creamy_alfredo_1781958600642.jpg',
    caption: 'Fettuccine Alfredo cooked with premium aged parmesan.',
    category: 'dishes',
  },
  {
    id: 'g2',
    image: '/src/assets/images/restaurant_interior_1781958580832.jpg',
    caption: 'Our elegant and intimate main dining setup.',
    category: 'interior',
  },
  {
    id: 'g3',
    image: '/src/assets/images/hero_steak_gourmet_1781958560784.jpg',
    caption: 'Prime ribeye cuts seared by master chefs.',
    category: 'dishes',
  },
  {
    id: 'g4',
    image: '/src/assets/images/beef_burger_1781958615596.jpg',
    caption: 'Juicy artisan burgers assembled on buttered brioche.',
    category: 'dishes',
  },
  {
    id: 'g5',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800',
    caption: 'The warm, relaxing ambience during evening hours.',
    category: 'atmosphere',
  },
  {
    id: 'g6',
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&q=80&w=800',
    caption: 'Unparalleled customer hospitality and wine service.',
    category: 'atmosphere',
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    author: 'Sarah Jenkins',
    role: 'Local Food Critic',
    text: 'Flavoro has redefined casual fine dining in our neighborhood. The Grilled Salmon was exceptionally moist, and the moody, elegant interior feels like a true oasis.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
  },
  {
    id: 'r2',
    author: 'David Vance',
    role: 'Gourmet Enthusiast',
    text: 'Unbelievable flavors. The truffle garlic bread combined with their classic beef burger makes for a highly satisfying feast. Plus, the service was wonderfully prompt and warm.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
  },
  {
    id: 'r3',
    author: 'Elena Rostova',
    role: 'Travel blogger',
    text: 'Finding premium food combined with this level of cozy atmosphere is rare. The Chocolate Lava Cake literally flows with liquid cocoa perfection. Highly recommended!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=150',
  },
];
